name: Build Alelaskuri APK

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system deps
        run: |
          sudo apt update
          sudo apt install -y git zip unzip openjdk-17-jdk \
          build-essential python3-pip autoconf libtool pkg-config

          pip install --upgrade pip
          pip install buildozer cython

      - name: Force python-for-android version
        run: |
          pip install python-for-android==2023.9.16

      - name: Clean build
        run: |
          rm -rf .buildozer
          buildozer init || true

      - name: Build APK
        run: |
          buildozer android clean
          buildozer -v android debug

      - uses: actions/upload-artifact@v4
        with:
          name: alelaskuri-apk
          path: bin/*.apk
